import React, { useState } from 'react';
import { 
  Layers, 
  Database, 
  Code, 
  Server, 
  Lightbulb, 
  Copy, 
  Check, 
  Download, 
  ArrowLeft, 
  RefreshCw, 
  Maximize2, 
  ZoomIn, 
  ZoomOut, 
  RotateCcw, 
  FileText, 
  ShieldCheck, 
  Cpu, 
  Boxes, 
  Sparkles, 
  ExternalLink,
  ChevronRight,
  Eye,
  CheckCircle2,
  AlertCircle,
  Terminal,
  Share2
} from 'lucide-react';
import { Mermaid } from './Mermaid';
import { AnalysisResult, TabType, Endpoint } from '../types';
import { motion, AnimatePresence } from 'motion/react';

interface ResultsWorkbenchProps {
  result: AnalysisResult;
  preview: string | null;
  fileName: string | null;
  onBack: () => void;
  onNewSynthesis: () => void;
}

export function ResultsWorkbench({ 
  result, 
  preview, 
  fileName, 
  onBack, 
  onNewSynthesis 
}: ResultsWorkbenchProps) {
  const [activeTab, setActiveTab] = useState<TabType>('diagram');
  const [copiedStates, setCopiedStates] = useState<{ [key: string]: boolean }>({});
  const [zoomLevel, setZoomLevel] = useState(1);
  const [selectedEndpoint, setSelectedEndpoint] = useState<Endpoint | null>(result.endpoints?.[0] || null);
  const [showSketchModal, setShowSketchModal] = useState(false);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => {
      setToastMessage(null);
    }, 2400);
  };

  const copyToClipboard = async (text: string, id: string, label = 'Copied to clipboard') => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedStates(prev => ({ ...prev, [id]: true }));
      showToast(label);
      setTimeout(() => {
        setCopiedStates(prev => ({ ...prev, [id]: false }));
      }, 2000);
    } catch (err) {
      console.error('Failed to copy text', err);
    }
  };

  const downloadFile = (filename: string, content: string, mimeType = 'text/plain') => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast(`Downloaded ${filename}`);
  };

  const exportAllBundle = () => {
    downloadFile('schema.prisma', result.prismaSchema);
    setTimeout(() => downloadFile('migration.sql', result.sqlSchema), 200);
    setTimeout(() => downloadFile('architecture.mmd', result.mermaidDiagram), 400);
    setTimeout(() => downloadFile('api_endpoints.json', JSON.stringify(result.endpoints, null, 2), 'application/json'), 600);
    showToast("Exported all architecture files");
  };

  const copyFullArchitectureMarkdown = () => {
    const fullMd = `# ${result.title}
Generated by ScribeSync

## Summary
${result.summary}

## 1. Visual Topology (Mermaid)
\`\`\`mermaid
${result.mermaidDiagram}
\`\`\`

## 2. Prisma Schema
\`\`\`prisma
${result.prismaSchema}
\`\`\`

## 3. PostgreSQL DDL Migration
\`\`\`sql
${result.sqlSchema}
\`\`\`

## 4. API Endpoints
${result.endpoints.map(e => `- **[${e.method}]** \`${e.path}\`: ${e.description}`).join('\n')}
`;
    copyToClipboard(fullMd, 'full_bundle', 'Full Architecture Markdown Copied!');
  };

  // Derive stats if not provided
  const entityCount = result.entities?.length || (result.prismaSchema.match(/model\s+\w+/g) || []).length || 4;
  const endpointCount = result.endpoints.length;

  return (
    <div className="min-h-screen bg-[#121110] text-[#FAF8F5] font-['Instrument_Sans',sans-serif] flex flex-col selection:bg-stone-700/50">
      
      {/* Toast Notification Banner */}
      <AnimatePresence>
        {toastMessage && (
          <motion.div 
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="fixed top-5 left-1/2 -translate-x-1/2 z-50 px-4 py-2 bg-stone-900 border border-stone-700 text-stone-100 rounded-xl shadow-2xl text-xs font-mono flex items-center gap-2 backdrop-blur-md"
          >
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>{toastMessage}</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Top Header Bar */}
      <header className="h-16 border-b border-stone-800/80 px-4 sm:px-8 flex items-center justify-between bg-[#181715]/90 backdrop-blur-md shrink-0 sticky top-0 z-30">
        <div className="flex items-center gap-3">
          <button 
            onClick={onBack}
            className="p-1.5 rounded-lg text-stone-400 hover:text-white hover:bg-stone-800 transition"
            title="Return to landing canvas"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          
          <div className="flex items-center gap-2.5">
            <span className="font-['Big_Shoulders_Display',sans-serif] tracking-[0.2em] text-white font-extrabold text-xl uppercase select-none">
              SCRIBESYNC
            </span>
            <span className="text-stone-700">/</span>
            <span className="text-xs font-mono text-emerald-400 bg-emerald-950/40 border border-emerald-800/50 px-2 py-0.5 rounded uppercase hidden sm:inline-block">
              SYNTHESIS WORKBENCH
            </span>
          </div>
        </div>

        {/* Global Toolbar Actions */}
        <div className="flex items-center gap-2 sm:gap-3">
          <button 
            onClick={exportAllBundle}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-stone-700/80 bg-stone-800/80 hover:bg-stone-700 text-stone-200 text-xs font-mono transition"
            title="Download .prisma, .sql, .mmd files"
          >
            <Download className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Export Bundle</span>
          </button>

          <button 
            onClick={copyFullArchitectureMarkdown}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-stone-800 bg-stone-900 hover:bg-stone-800 text-stone-300 text-xs font-mono transition"
            title="Copy full synthesis markdown"
          >
            {copiedStates['full_bundle'] ? (
              <Check className="w-3.5 h-3.5 text-emerald-400" />
            ) : (
              <Copy className="w-3.5 h-3.5" />
            )}
            <span className="hidden sm:inline">Copy All</span>
          </button>

          <button 
            onClick={onNewSynthesis}
            className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-[#383531] text-stone-200 hover:bg-stone-200 hover:text-stone-900 transition font-sans font-medium text-xs shadow-md"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            <span>New Sketch</span>
          </button>
        </div>
      </header>

      {/* Main Workspace Split Body */}
      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
        
        {/* Left Inspector Sidebar (Architecture Telemetry & Original Sketch) */}
        <aside className="w-full lg:w-80 bg-black border-r border-stone-800 p-5 flex flex-col gap-6 overflow-y-auto shrink-0 z-10">
          
          {/* Sketch Card Thumbnail */}
          <div className="bg-[#0e0e0d] border border-stone-800 rounded-xl p-4 shadow-sm">
            <div className="flex items-center justify-between mb-3">
              <span className="text-[11px] font-mono text-stone-300 uppercase tracking-wider flex items-center gap-1.5 font-medium">
                <Eye className="w-3.5 h-3.5 text-stone-400" />
                Source Sketch
              </span>
              <button 
                onClick={() => setShowSketchModal(true)}
                className="text-[10px] font-mono text-stone-400 hover:text-white flex items-center gap-1"
              >
                <Maximize2 className="w-3 h-3" />
                Inspect
              </button>
            </div>

            <div 
              onClick={() => setShowSketchModal(true)}
              className="relative w-full h-36 rounded-lg bg-black border border-stone-800 overflow-hidden cursor-pointer group flex items-center justify-center"
            >
              {preview ? (
                <img 
                  src={preview} 
                  alt="Original Sketch" 
                  className="w-full h-full object-cover group-hover:scale-105 transition duration-300"
                />
              ) : (
                <div className="flex flex-col items-center justify-center text-center p-3">
                  <FileText className="w-8 h-8 text-stone-600 mb-1" />
                  <span className="text-xs text-stone-400 font-medium">Napkin Diagram</span>
                  <span className="text-[10px] text-stone-600 font-mono">Simulated Whiteboard</span>
                </div>
              )}
              <div className="absolute inset-0 bg-black/70 flex items-center justify-center opacity-0 group-hover:opacity-100 transition">
                <span className="text-xs font-mono text-white flex items-center gap-1 bg-stone-900 px-2.5 py-1 rounded border border-stone-700">
                  <Maximize2 className="w-3 h-3" /> Zoom
                </span>
              </div>
            </div>
          </div>

          {/* Quick Metrics Bento */}
          <div className="space-y-3">
            <span className="text-[11px] font-mono text-stone-400 uppercase tracking-wider font-medium">
              Architecture Metrics
            </span>
            <div className="grid grid-cols-2 gap-2">
              <div className="bg-[#0e0e0d] border border-stone-800 p-3 rounded-xl">
                <span className="text-[10px] font-mono text-stone-400 uppercase">Entities</span>
                <p className="text-lg font-bold text-white font-mono">{entityCount}</p>
              </div>
              <div className="bg-[#0e0e0d] border border-stone-800 p-3 rounded-xl">
                <span className="text-[10px] font-mono text-stone-400 uppercase">API Routes</span>
                <p className="text-lg font-bold text-blue-400 font-mono">{endpointCount}</p>
              </div>
              <div className="bg-[#0e0e0d] border border-stone-800 p-3 rounded-xl">
                <span className="text-[10px] font-mono text-stone-400 uppercase">Target DB</span>
                <p className="text-xs font-bold text-emerald-400 font-mono mt-1">PostgreSQL 14+</p>
              </div>
              <div className="bg-[#0e0e0d] border border-stone-800 p-3 rounded-xl">
                <span className="text-[10px] font-mono text-stone-400 uppercase">ORM Client</span>
                <p className="text-xs font-bold text-amber-400 font-mono mt-1">Prisma v5</p>
              </div>
            </div>
          </div>

          {/* Schema Integrity Verification */}
          <div className="bg-[#0e0e0d] border border-stone-800 rounded-xl p-4 space-y-2.5">
            <span className="text-[11px] font-mono text-stone-300 uppercase tracking-wider flex items-center gap-1.5 font-medium">
              <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
              Integrity Checks
            </span>
            <div className="space-y-2 text-xs font-sans text-stone-200">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                <span>Zero circular dependency cycles</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                <span>UUID v4 Primary Keys generated</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                <span>Cascading delete foreign rules</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                <span>B-Tree indexes mapped to lookups</span>
              </div>
            </div>
          </div>

          {/* Detected Models List */}
          {result.entities && result.entities.length > 0 && (
            <div className="space-y-2">
              <span className="text-[11px] font-mono text-stone-400 uppercase tracking-wider font-medium">
                Recognized Models ({result.entities.length})
              </span>
              <div className="space-y-1.5">
                {result.entities.map((ent, i) => (
                  <div key={i} className="flex items-center justify-between p-2.5 rounded-lg bg-[#0e0e0d] border border-stone-800 text-xs">
                    <span className="font-mono text-stone-100 font-medium">{ent.name}</span>
                    <span className="text-[10px] font-mono text-stone-400">{ent.fieldsCount} attrs</span>
                  </div>
                ))}
              </div>
            </div>
          )}

        </aside>

        {/* Main Content Workspace */}
        <main className="flex-1 flex flex-col overflow-hidden bg-[#121110]">
          
          {/* Architecture Title Header */}
          <div className="p-6 border-b border-stone-800/80 bg-[#181715]/40 flex flex-col sm:flex-row sm:items-center justify-between gap-4 shrink-0">
            <div>
              <h1 className="text-xl sm:text-2xl font-['Instrument_Serif',serif] font-bold text-white tracking-tight">
                {result.title}
              </h1>
              <p className="text-xs sm:text-sm text-stone-400 mt-1 max-w-3xl leading-relaxed">
                {result.summary}
              </p>
            </div>
          </div>

          {/* Navigation Tab Bar */}
          <div className="flex border-b border-stone-800/80 bg-[#141311] overflow-x-auto no-scrollbar shrink-0">
            <button
              onClick={() => setActiveTab('diagram')}
              className={`flex items-center gap-2 px-6 py-3.5 text-xs font-mono uppercase tracking-wider transition-colors whitespace-nowrap ${
                activeTab === 'diagram' 
                  ? 'bg-[#1e1d1a] text-white border-b-2 border-stone-300' 
                  : 'text-stone-500 hover:text-stone-300 hover:bg-stone-900/40'
              }`}
            >
              <Layers className="w-4 h-4 text-stone-400" />
              Visual Diagram
            </button>

            <button
              onClick={() => setActiveTab('prisma')}
              className={`flex items-center gap-2 px-6 py-3.5 text-xs font-mono uppercase tracking-wider transition-colors whitespace-nowrap ${
                activeTab === 'prisma' 
                  ? 'bg-[#1e1d1a] text-white border-b-2 border-stone-300' 
                  : 'text-stone-500 hover:text-stone-300 hover:bg-stone-900/40'
              }`}
            >
              <Database className="w-4 h-4 text-stone-400" />
              Prisma Schema
            </button>

            <button
              onClick={() => setActiveTab('sql')}
              className={`flex items-center gap-2 px-6 py-3.5 text-xs font-mono uppercase tracking-wider transition-colors whitespace-nowrap ${
                activeTab === 'sql' 
                  ? 'bg-[#1e1d1a] text-white border-b-2 border-stone-300' 
                  : 'text-stone-500 hover:text-stone-300 hover:bg-stone-900/40'
              }`}
            >
              <Code className="w-4 h-4 text-stone-400" />
              SQL Migration
            </button>

            <button
              onClick={() => setActiveTab('api')}
              className={`flex items-center gap-2 px-6 py-3.5 text-xs font-mono uppercase tracking-wider transition-colors whitespace-nowrap ${
                activeTab === 'api' 
                  ? 'bg-[#1e1d1a] text-white border-b-2 border-stone-300' 
                  : 'text-stone-500 hover:text-stone-300 hover:bg-stone-900/40'
              }`}
            >
              <Server className="w-4 h-4 text-stone-400" />
              API Endpoints ({result.endpoints.length})
            </button>

            <button
              onClick={() => setActiveTab('insights')}
              className={`flex items-center gap-2 px-6 py-3.5 text-xs font-mono uppercase tracking-wider transition-colors whitespace-nowrap ${
                activeTab === 'insights' 
                  ? 'bg-[#1e1d1a] text-white border-b-2 border-stone-300' 
                  : 'text-stone-500 hover:text-stone-300 hover:bg-stone-900/40'
              }`}
            >
              <Lightbulb className="w-4 h-4 text-stone-400" />
              System Insights
            </button>
          </div>

          {/* Active Tab Panel Body */}
          <div className="flex-1 overflow-y-auto p-4 sm:p-6 bg-[#0e0d0c] relative flex flex-col">
            
            {/* TAB 1: VISUAL MERMAID DIAGRAM */}
            {activeTab === 'diagram' && (
              <div className="flex-1 flex flex-col gap-4">
                <div className="flex items-center justify-between bg-[#181715] border border-stone-800 p-2.5 rounded-xl text-xs font-mono">
                  <div className="flex items-center gap-2">
                    <span className="text-stone-500">View Controls:</span>
                    <button 
                      onClick={() => setZoomLevel(prev => Math.min(prev + 0.15, 2.0))}
                      className="p-1.5 rounded hover:bg-stone-800 text-stone-300 transition"
                      title="Zoom In"
                    >
                      <ZoomIn className="w-4 h-4" />
                    </button>
                    <button 
                      onClick={() => setZoomLevel(prev => Math.max(prev - 0.15, 0.6))}
                      className="p-1.5 rounded hover:bg-stone-800 text-stone-300 transition"
                      title="Zoom Out"
                    >
                      <ZoomOut className="w-4 h-4" />
                    </button>
                    <button 
                      onClick={() => setZoomLevel(1)}
                      className="p-1.5 rounded hover:bg-stone-800 text-stone-300 transition"
                      title="Reset Zoom"
                    >
                      <RotateCcw className="w-4 h-4" />
                    </button>
                    <span className="text-stone-500 ml-2">{Math.round(zoomLevel * 100)}%</span>
                  </div>

                  <div className="flex items-center gap-2">
                    <button 
                      onClick={() => copyToClipboard(result.mermaidDiagram, 'mmd_raw', 'Mermaid Syntax Copied')}
                      className="px-2.5 py-1 rounded bg-[#252320] hover:bg-stone-700 text-stone-300 transition border border-stone-700 flex items-center gap-1.5"
                    >
                      <Copy className="w-3.5 h-3.5" />
                      <span>Copy Mermaid</span>
                    </button>
                    <button 
                      onClick={() => downloadFile('architecture.mmd', result.mermaidDiagram)}
                      className="px-2.5 py-1 rounded bg-[#252320] hover:bg-stone-700 text-stone-300 transition border border-stone-700 flex items-center gap-1.5"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>.mmd</span>
                    </button>
                  </div>
                </div>

                <div className="flex-1 min-h-[460px] bg-[#141311] rounded-2xl border border-stone-800/80 p-6 flex items-center justify-center overflow-auto relative">
                  <div 
                    style={{ transform: `scale(${zoomLevel})`, transformOrigin: 'center center', transition: 'transform 0.2s ease-out' }}
                    className="w-full flex items-center justify-center"
                  >
                    <Mermaid chart={result.mermaidDiagram} />
                  </div>
                </div>
              </div>
            )}

            {/* TAB 2: PRISMA SCHEMA */}
            {activeTab === 'prisma' && (
              <div className="flex-1 flex flex-col relative">
                <div className="flex items-center justify-between pb-3">
                  <span className="text-xs font-mono text-stone-400">
                    schema.prisma • PostgreSQL Datasource
                  </span>
                  <div className="flex items-center gap-2">
                    <button 
                      onClick={() => copyToClipboard(result.prismaSchema, 'prisma_code')}
                      className="px-3 py-1.5 rounded-lg bg-[#252320] hover:bg-stone-700 text-stone-200 text-xs font-mono transition border border-stone-700 flex items-center gap-1.5"
                    >
                      {copiedStates['prisma_code'] ? (
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                      ) : (
                        <Copy className="w-3.5 h-3.5" />
                      )}
                      <span>{copiedStates['prisma_code'] ? 'Copied' : 'Copy Schema'}</span>
                    </button>
                    <button 
                      onClick={() => downloadFile('schema.prisma', result.prismaSchema)}
                      className="px-3 py-1.5 rounded-lg bg-[#252320] hover:bg-stone-700 text-stone-200 text-xs font-mono transition border border-stone-700 flex items-center gap-1.5"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Download</span>
                    </button>
                  </div>
                </div>

                <pre className="flex-1 p-6 rounded-xl bg-[#141311] border border-stone-800/80 overflow-x-auto text-xs text-stone-200 font-['JetBrains_Mono'] leading-relaxed shadow-inner">
                  <code>{result.prismaSchema}</code>
                </pre>
              </div>
            )}

            {/* TAB 3: SQL MIGRATION */}
            {activeTab === 'sql' && (
              <div className="flex-1 flex flex-col relative">
                <div className="flex items-center justify-between pb-3">
                  <span className="text-xs font-mono text-stone-400">
                    migration.sql • DDL & Foreign Constraints
                  </span>
                  <div className="flex items-center gap-2">
                    <button 
                      onClick={() => copyToClipboard(result.sqlSchema, 'sql_code')}
                      className="px-3 py-1.5 rounded-lg bg-[#252320] hover:bg-stone-700 text-stone-200 text-xs font-mono transition border border-stone-700 flex items-center gap-1.5"
                    >
                      {copiedStates['sql_code'] ? (
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                      ) : (
                        <Copy className="w-3.5 h-3.5" />
                      )}
                      <span>{copiedStates['sql_code'] ? 'Copied' : 'Copy SQL'}</span>
                    </button>
                    <button 
                      onClick={() => downloadFile('migration.sql', result.sqlSchema)}
                      className="px-3 py-1.5 rounded-lg bg-[#252320] hover:bg-stone-700 text-stone-200 text-xs font-mono transition border border-stone-700 flex items-center gap-1.5"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Download</span>
                    </button>
                  </div>
                </div>

                <pre className="flex-1 p-6 rounded-xl bg-[#141311] border border-stone-800/80 overflow-x-auto text-xs text-stone-200 font-['JetBrains_Mono'] leading-relaxed shadow-inner">
                  <code>{result.sqlSchema}</code>
                </pre>
              </div>
            )}

            {/* TAB 4: API ENDPOINTS EXPLORER */}
            {activeTab === 'api' && (
              <div className="flex-1 flex flex-col lg:flex-row gap-6">
                
                {/* Endpoint Table */}
                <div className="flex-1 bg-[#141311] rounded-xl border border-stone-800/80 overflow-hidden flex flex-col">
                  <div className="p-3 border-b border-stone-800 bg-[#181715] flex items-center justify-between text-xs font-mono text-stone-400">
                    <span>Generated REST API Routes</span>
                    <span>{result.endpoints.length} Routes</span>
                  </div>
                  
                  <div className="overflow-x-auto flex-1">
                    <table className="w-full text-left border-collapse font-['JetBrains_Mono']">
                      <thead>
                        <tr className="bg-[#181715]/60 border-b border-stone-800">
                          <th className="px-4 py-3 text-[10px] font-semibold text-stone-500 uppercase">Method</th>
                          <th className="px-4 py-3 text-[10px] font-semibold text-stone-500 uppercase">Path</th>
                          <th className="px-4 py-3 text-[10px] font-semibold text-stone-500 uppercase">Description</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-stone-800/60 text-xs">
                        {result.endpoints.map((endpoint, i) => {
                          const isSelected = selectedEndpoint?.path === endpoint.path && selectedEndpoint?.method === endpoint.method;
                          return (
                            <tr 
                              key={i} 
                              onClick={() => setSelectedEndpoint(endpoint)}
                              className={`cursor-pointer transition-colors ${
                                isSelected ? 'bg-stone-800/60' : 'hover:bg-stone-900/40'
                              }`}
                            >
                              <td className="px-4 py-3 whitespace-nowrap">
                                <span className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold ${
                                  endpoint.method === 'GET' ? 'bg-blue-950 text-blue-300 border border-blue-800/60' :
                                  endpoint.method === 'POST' ? 'bg-emerald-950 text-emerald-300 border border-emerald-800/60' :
                                  endpoint.method === 'PUT' ? 'bg-amber-950 text-amber-300 border border-amber-800/60' :
                                  endpoint.method === 'DELETE' ? 'bg-red-950 text-red-300 border border-red-800/60' :
                                  'bg-stone-800 text-stone-300'
                                }`}>
                                  {endpoint.method}
                                </span>
                              </td>
                              <td className="px-4 py-3 whitespace-nowrap text-stone-200 font-medium">
                                {endpoint.path}
                              </td>
                              <td className="px-4 py-3 text-stone-400 font-sans text-xs">
                                {endpoint.description}
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* Endpoint Interactive Inspector */}
                {selectedEndpoint && (
                  <div className="w-full lg:w-96 bg-[#181715] rounded-xl border border-stone-800 p-5 flex flex-col gap-4">
                    <div className="flex items-center justify-between pb-3 border-b border-stone-800">
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-stone-800 text-stone-200 font-mono">
                          {selectedEndpoint.method}
                        </span>
                        <span className="text-xs font-mono text-stone-300 truncate max-w-[180px]">
                          {selectedEndpoint.path}
                        </span>
                      </div>
                      <button 
                        onClick={() => {
                          const curl = `curl -X ${selectedEndpoint.method} "https://api.yourdomain.com${selectedEndpoint.path}"`;
                          copyToClipboard(curl, 'curl_copy', 'cURL snippet copied');
                        }}
                        className="text-[11px] font-mono text-stone-400 hover:text-white flex items-center gap-1"
                        title="Copy cURL command"
                      >
                        <Terminal className="w-3 h-3" /> cURL
                      </button>
                    </div>

                    <div>
                      <span className="text-[10px] font-mono text-stone-500 uppercase">Description</span>
                      <p className="text-xs text-stone-300 mt-1 font-sans">
                        {selectedEndpoint.description}
                      </p>
                    </div>

                    {selectedEndpoint.requestBody && (
                      <div>
                        <span className="text-[10px] font-mono text-stone-500 uppercase">Sample Request Body</span>
                        <pre className="mt-1 p-3 rounded bg-[#0e0d0c] border border-stone-800 text-[11px] font-mono text-stone-300 overflow-x-auto">
                          <code>{selectedEndpoint.requestBody}</code>
                        </pre>
                      </div>
                    )}

                    {selectedEndpoint.responseBody && (
                      <div>
                        <span className="text-[10px] font-mono text-stone-500 uppercase">Sample 200 OK Response</span>
                        <pre className="mt-1 p-3 rounded bg-[#0e0d0c] border border-stone-800 text-[11px] font-mono text-emerald-400/90 overflow-x-auto">
                          <code>{selectedEndpoint.responseBody}</code>
                        </pre>
                      </div>
                    )}
                  </div>
                )}

              </div>
            )}

            {/* TAB 5: ARCHITECTURE INSIGHTS */}
            {activeTab === 'insights' && (
              <div className="flex-1 flex flex-col gap-4">
                <div className="bg-[#181715] border border-stone-800/80 rounded-xl p-5">
                  <h2 className="text-lg font-bold text-white font-['Instrument_Sans'] mb-1">
                    System Architecture Recommendations
                  </h2>
                  <p className="text-xs text-stone-400">
                    Automated performance, indexing, caching and security heuristics generated from your whiteboard entities.
                  </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {(result.insights || [
                    {
                      category: 'caching',
                      title: 'Hot Entity Query Caching',
                      description: 'Implement distributed Redis caching layer for read-heavy entities to minimize database connection pressure.',
                      impact: 'High'
                    },
                    {
                      category: 'indexing',
                      title: 'Foreign Key B-Tree Indexing',
                      description: 'Composite foreign key indexes generated automatically across all relation pivots.',
                      impact: 'High'
                    },
                    {
                      category: 'scaling',
                      title: 'Asynchronous Task Offloading',
                      description: 'Decouple long-running tasks such as notifications and reporting with worker queues.',
                      impact: 'Medium'
                    },
                    {
                      category: 'security',
                      title: 'Row-Level Ownership Validation',
                      description: 'Enforce tenant/user ownership assertions in API middleware before mutative database operations.',
                      impact: 'High'
                    }
                  ]).map((item, idx) => (
                    <div key={idx} className="bg-[#181715] border border-stone-800/80 rounded-xl p-5 flex flex-col justify-between">
                      <div>
                        <div className="flex items-center justify-between mb-2">
                          <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-stone-900 border border-stone-800 text-stone-400">
                            {item.category}
                          </span>
                          <span className={`text-[10px] font-mono px-2 py-0.5 rounded ${
                            item.impact === 'High' ? 'text-amber-400 bg-amber-950/40 border border-amber-800/40' : 'text-stone-400 bg-stone-900'
                          }`}>
                            {item.impact} Impact
                          </span>
                        </div>
                        <h3 className="text-sm font-semibold text-white mt-2">
                          {item.title}
                        </h3>
                        <p className="text-xs text-stone-400 mt-1 leading-relaxed">
                          {item.description}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

          </div>
        </main>
      </div>

      {/* Sketch Zoom Modal */}
      <AnimatePresence>
        {showSketchModal && (
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={() => setShowSketchModal(false)}
            className="fixed inset-0 z-50 bg-[#121110]/90 backdrop-blur-md flex items-center justify-center p-6"
          >
            <div 
              onClick={(e) => e.stopPropagation()}
              className="max-w-4xl w-full bg-[#181715] border border-stone-800 rounded-2xl p-6 shadow-2xl flex flex-col gap-4"
            >
              <div className="flex items-center justify-between pb-3 border-b border-stone-800">
                <span className="text-sm font-mono text-white">Original Whiteboard Sketch Artifact</span>
                <button 
                  onClick={() => setShowSketchModal(false)}
                  className="p-1 rounded text-stone-400 hover:text-white"
                >
                  ✕
                </button>
              </div>

              <div className="w-full max-h-[70vh] rounded-xl overflow-hidden bg-black flex items-center justify-center">
                {preview ? (
                  <img src={preview} alt="Enlarged Whiteboard Sketch" className="max-w-full max-h-[70vh] object-contain" />
                ) : (
                  <div className="p-12 text-center text-stone-500 font-mono text-sm">
                    Simulated Whiteboard Canvas
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
