import { AnalysisResult } from '../types';

export interface SamplePreset {
  id: string;
  name: string;
  category: string;
  description: string;
  thumbnailSvg?: string;
  result: AnalysisResult;
}

export const SAMPLE_PRESETS: SamplePreset[] = [
  {
    id: 'ecommerce',
    name: 'E-Commerce Microservices & Orders',
    category: 'E-Commerce & Retail',
    description: 'Relational mapping for User accounts, Catalogs, Orders, Line Items, and Stripe Payments.',
    result: {
      title: 'E-Commerce Microservices Architecture',
      summary: 'A resilient event-driven microservices architecture decoupling customer profiles, catalog management, inventory allocation, and order execution pipelines with relational ACID consistency.',
      mermaidDiagram: `erDiagram
    USER ||--o{ ORDER : places
    ORDER ||--|{ ORDER_ITEM : contains
    PRODUCT ||--o{ ORDER_ITEM : "included in"
    USER ||--o| PAYMENT_METHOD : "has default"
    ORDER ||--|| INVOICE : generates
    
    USER {
        uuid id PK
        string email UK
        string name
        string role
        timestamp createdAt
    }
    
    PRODUCT {
        uuid id PK
        string sku UK
        string name
        float price
        int stock
        boolean active
    }
    
    ORDER {
        uuid id PK
        uuid userId FK
        string status
        float subtotal
        float tax
        float total
        timestamp createdAt
    }
    
    ORDER_ITEM {
        uuid id PK
        uuid orderId FK
        uuid productId FK
        int quantity
        float unitPrice
    }
    
    PAYMENT_METHOD {
        uuid id PK
        uuid userId FK
        string provider
        string token
        boolean isDefault
    }
    
    INVOICE {
        uuid id PK
        uuid orderId FK
        string invoiceNumber UK
        timestamp issuedAt
        string pdfUrl
    }`,
      prismaSchema: `// Prisma Schema generated by ScribeSync
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum OrderStatus {
  PENDING
  AUTHORIZED
  PAID
  FULFILLED
  CANCELLED
}

enum Role {
  CUSTOMER
  ADMIN
  WAREHOUSE_STAFF
}

model User {
  id             String          @id @default(uuid()) @db.Uuid
  email          String          @unique
  name           String?
  role           Role            @default(CUSTOMER)
  createdAt      DateTime        @default(now())
  updatedAt      DateTime        @updatedAt
  orders         Order[]
  paymentMethods PaymentMethod[]

  @@index([email])
}

model Product {
  id         String      @id @default(uuid()) @db.Uuid
  sku        String      @unique
  name       String
  price      Decimal     @db.Decimal(10, 2)
  stock      Int         @default(0)
  active     Boolean     @default(true)
  createdAt  DateTime    @default(now())
  updatedAt  DateTime    @updatedAt
  orderItems OrderItem[]

  @@index([sku])
  @@index([active])
}

model Order {
  id        String      @id @default(uuid()) @db.Uuid
  userId    String      @db.Uuid
  user      User        @relation(fields: [userId], references: [id], onDelete: Cascade)
  status    OrderStatus @default(PENDING)
  subtotal  Decimal     @db.Decimal(10, 2)
  tax       Decimal     @db.Decimal(10, 2)
  total     Decimal     @db.Decimal(10, 2)
  createdAt DateTime    @default(now())
  updatedAt DateTime    @updatedAt
  items     OrderItem[]
  invoice   Invoice?

  @@index([userId])
  @@index([status])
  @@index([createdAt])
}

model OrderItem {
  id        String   @id @default(uuid()) @db.Uuid
  orderId   String   @db.Uuid
  order     Order    @relation(fields: [orderId], references: [id], onDelete: Cascade)
  productId String   @db.Uuid
  product   Product  @relation(fields: [productId], references: [id])
  quantity  Int      @default(1)
  unitPrice Decimal  @db.Decimal(10, 2)

  @@index([orderId])
  @@index([productId])
}

model PaymentMethod {
  id        String   @id @default(uuid()) @db.Uuid
  userId    String   @db.Uuid
  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
  provider  String   // e.g. 'STRIPE', 'PAYPAL'
  token     String
  isDefault Boolean  @default(false)
  createdAt DateTime @default(now())

  @@index([userId])
}

model Invoice {
  id            String   @id @default(uuid()) @db.Uuid
  orderId       String   @unique @db.Uuid
  order         Order    @relation(fields: [orderId], references: [id], onDelete: Cascade)
  invoiceNumber String   @unique
  issuedAt      DateTime @default(now())
  pdfUrl        String?
}`,
      sqlSchema: `-- ScribeSync SQL Migration DDL
-- Target: PostgreSQL 14+ / Supabase / Neon / Cloud SQL

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enums
CREATE TYPE "OrderStatus" AS ENUM ('PENDING', 'AUTHORIZED', 'PAID', 'FULFILLED', 'CANCELLED');
CREATE TYPE "UserRole" AS ENUM ('CUSTOMER', 'ADMIN', 'WAREHOUSE_STAFF');

-- User Table
CREATE TABLE IF NOT EXISTS "users" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "name" VARCHAR(100),
    "role" "UserRole" DEFAULT 'CUSTOMER' NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_users_email" ON "users"("email");

-- Product Table
CREATE TABLE IF NOT EXISTS "products" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "sku" VARCHAR(64) UNIQUE NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "price" NUMERIC(10, 2) NOT NULL CHECK ("price" >= 0),
    "stock" INTEGER DEFAULT 0 NOT NULL CHECK ("stock" >= 0),
    "active" BOOLEAN DEFAULT TRUE NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_products_sku" ON "products"("sku");
CREATE INDEX IF NOT EXISTS "idx_products_active" ON "products"("active");

-- Order Table
CREATE TABLE IF NOT EXISTS "orders" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "user_id" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "status" "OrderStatus" DEFAULT 'PENDING' NOT NULL,
    "subtotal" NUMERIC(10, 2) NOT NULL,
    "tax" NUMERIC(10, 2) NOT NULL,
    "total" NUMERIC(10, 2) NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_orders_user_id" ON "orders"("user_id");
CREATE INDEX IF NOT EXISTS "idx_orders_status" ON "orders"("status");
CREATE INDEX IF NOT EXISTS "idx_orders_created_at" ON "orders"("created_at" DESC);

-- Order Items Table
CREATE TABLE IF NOT EXISTS "order_items" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "order_id" UUID NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
    "product_id" UUID NOT NULL REFERENCES "products"("id") ON DELETE RESTRICT,
    "quantity" INTEGER DEFAULT 1 NOT NULL CHECK ("quantity" > 0),
    "unit_price" NUMERIC(10, 2) NOT NULL CHECK ("unit_price" >= 0)
);
CREATE INDEX IF NOT EXISTS "idx_order_items_order_id" ON "order_items"("order_id");
CREATE INDEX IF NOT EXISTS "idx_order_items_product_id" ON "order_items"("product_id");

-- Payment Method Table
CREATE TABLE IF NOT EXISTS "payment_methods" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "user_id" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "provider" VARCHAR(32) NOT NULL,
    "token" VARCHAR(255) NOT NULL,
    "is_default" BOOLEAN DEFAULT FALSE NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS "idx_payment_methods_user" ON "payment_methods"("user_id");

-- Invoice Table
CREATE TABLE IF NOT EXISTS "invoices" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "order_id" UUID UNIQUE NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
    "invoice_number" VARCHAR(64) UNIQUE NOT NULL,
    "issued_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "pdf_url" TEXT
);`,
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/orders',
          description: 'Fetch paginated orders with filter by status and customer ID.',
          requestBody: '// Query Params: { page: 1, limit: 20, status: "PAID" }',
          responseBody: '{\n  "data": [{ "id": "uuid", "total": 129.99, "status": "PAID" }],\n  "pagination": { "page": 1, "total": 142 }\n}'
        },
        {
          method: 'POST',
          path: '/api/v1/orders',
          description: 'Create a new checkout order with atomic line item verification and inventory reservation.',
          requestBody: '{\n  "userId": "usr_9981",\n  "items": [{ "productId": "prod_1", "quantity": 2 }],\n  "paymentMethodId": "pm_883"\n}',
          responseBody: '{\n  "orderId": "ord_9182",\n  "status": "AUTHORIZED",\n  "total": 240.00\n}'
        },
        {
          method: 'GET',
          path: '/api/v1/products',
          description: 'Public catalog search with full-text search indexing and inventory counts.',
          requestBody: '// Query: { search: "mechanical keyboard", inStockOnly: true }',
          responseBody: '{\n  "items": [{ "id": "uuid", "name": "Keychron Q1", "price": 189.00, "stock": 14 }]\n}'
        },
        {
          method: 'POST',
          path: '/api/v1/payments/webhook',
          description: 'Stripe webhook receiver for asynchronous charge.succeeded and invoice generation.',
          requestBody: '{\n  "type": "payment_intent.succeeded",\n  "data": { "object": { "id": "pi_123" } }\n}',
          responseBody: '{\n  "received": true\n}'
        },
        {
          method: 'DELETE',
          path: '/api/v1/orders/:id',
          description: 'Soft-cancel an authorized order before dispatch and release stock locks.',
          requestBody: '{\n  "reason": "Customer cancellation request"\n}',
          responseBody: '{\n  "id": "ord_9182",\n  "status": "CANCELLED",\n  "refunded": true\n}'
        }
      ],
      entities: [
        { name: 'User', fieldsCount: 6, relationships: ['1:N Order', '1:N PaymentMethod'] },
        { name: 'Product', fieldsCount: 7, relationships: ['1:N OrderItem'] },
        { name: 'Order', fieldsCount: 8, relationships: ['N:1 User', '1:N OrderItem', '1:1 Invoice'] },
        { name: 'OrderItem', fieldsCount: 5, relationships: ['N:1 Order', 'N:1 Product'] },
        { name: 'PaymentMethod', fieldsCount: 6, relationships: ['N:1 User'] },
        { name: 'Invoice', fieldsCount: 5, relationships: ['1:1 Order'] }
      ],
      insights: [
        {
          category: 'caching',
          title: 'Product Catalog Redis Caching',
          description: 'Cache high-velocity product queries (`/api/v1/products`) with TTL of 60s to prevent database contention during traffic surges.',
          impact: 'High'
        },
        {
          category: 'indexing',
          title: 'Compound Index for Order Lookups',
          description: 'Added composite indexing on `orders(user_id, created_at DESC)` to enable instantaneous checkout history pagination.',
          impact: 'High'
        },
        {
          category: 'scaling',
          title: 'Asynchronous Invoice Generation',
          description: 'Queue invoice PDF creation on a background BullMQ / Cloud Tasks worker so checkout response latency stays under 100ms.',
          impact: 'Medium'
        },
        {
          category: 'security',
          title: 'Payment Token Isolation',
          description: 'Zero raw credit card data stored; schema securely binds provider tokens with row-level customer ownership constraints.',
          impact: 'High'
        }
      ],
      stats: {
        totalEntities: 6,
        totalRelations: 7,
        totalEndpoints: 5,
        queryComplexityScore: 'O(1) Indexed Lookups'
      }
    }
  },
  {
    id: 'saas_auth',
    name: 'Multi-Tenant SaaS & RBAC Platform',
    category: 'SaaS & Organizations',
    description: 'Workspaces, Tenants, Users, Custom Roles, API Keys & Audit Trail logs.',
    result: {
      title: 'Multi-Tenant SaaS with RBAC & Audit Ledger',
      summary: 'Isolated multi-workspace data model featuring granular permission sets, team invitations, hashed API key authentication, and an append-only audit event log.',
      mermaidDiagram: `erDiagram
    ORGANIZATION ||--o{ WORKSPACE : contains
    WORKSPACE ||--o{ MEMBERSHIP : has
    USER ||--o{ MEMBERSHIP : belongs_to
    ROLE ||--o{ MEMBERSHIP : grants
    WORKSPACE ||--o{ API_KEY : issues
    WORKSPACE ||--o{ AUDIT_LOG : tracks
    
    ORGANIZATION {
        uuid id PK
        string slug UK
        string name
        string plan
    }
    
    WORKSPACE {
        uuid id PK
        uuid orgId FK
        string name
        boolean active
    }
    
    USER {
        uuid id PK
        string email UK
        string name
        string avatarUrl
    }
    
    ROLE {
        uuid id PK
        string name
        string permissions
    }
    
    MEMBERSHIP {
        uuid id PK
        uuid userId FK
        uuid workspaceId FK
        uuid roleId FK
    }
    
    API_KEY {
        uuid id PK
        uuid workspaceId FK
        string keyHash
        string prefix
        timestamp expiresAt
    }
    
    AUDIT_LOG {
        uuid id PK
        uuid workspaceId FK
        string actorId
        string action
        jsonb metadata
        timestamp recordedAt
    }`,
      prismaSchema: `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Organization {
  id         String      @id @default(uuid()) @db.Uuid
  slug       String      @unique
  name       String
  plan       String      @default("FREE")
  workspaces Workspace[]
  createdAt  DateTime    @default(now())
}

model Workspace {
  id          String        @id @default(uuid()) @db.Uuid
  orgId       String        @db.Uuid
  organization Organization @relation(fields: [orgId], references: [id], onDelete: Cascade)
  name        String
  active      Boolean       @default(true)
  memberships Membership[]
  apiKeys     ApiKey[]
  auditLogs   AuditLog[]

  @@index([orgId])
}

model User {
  id          String       @id @default(uuid()) @db.Uuid
  email       String       @unique
  name        String?
  avatarUrl   String?
  memberships Membership[]
  createdAt   DateTime     @default(now())
}

model Role {
  id          String       @id @default(uuid()) @db.Uuid
  name        String       // ADMIN, MEMBER, VIEWER, BILLING
  permissions String[]     // Scopes: ['read:all', 'write:projects']
  memberships Membership[]
}

model Membership {
  id          String    @id @default(uuid()) @db.Uuid
  userId      String    @db.Uuid
  user        User      @relation(fields: [userId], references: [id], onDelete: Cascade)
  workspaceId String    @db.Uuid
  workspace   Workspace @relation(fields: [workspaceId], references: [id], onDelete: Cascade)
  roleId      String    @db.Uuid
  role        Role      @relation(fields: [roleId], references: [id])
  joinedAt    DateTime  @default(now())

  @@unique([userId, workspaceId])
  @@index([workspaceId])
}

model ApiKey {
  id          String    @id @default(uuid()) @db.Uuid
  workspaceId String    @db.Uuid
  workspace   Workspace @relation(fields: [workspaceId], references: [id], onDelete: Cascade)
  prefix      String    // e.g. "sk_live_5a8"
  keyHash     String    @unique
  name        String
  expiresAt   DateTime?
  createdAt   DateTime  @default(now())

  @@index([workspaceId])
}

model AuditLog {
  id          String    @id @default(uuid()) @db.Uuid
  workspaceId String    @db.Uuid
  workspace   Workspace @relation(fields: [workspaceId], references: [id], onDelete: Cascade)
  actorId     String
  action      String    // "workspace.created", "member.invited"
  metadata    Json      @default("{}")
  recordedAt  DateTime  @default(now())

  @@index([workspaceId, recordedAt])
}`,
      sqlSchema: `-- Multi-Tenant SaaS SQL Schema
CREATE TABLE "organizations" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "slug" VARCHAR(64) UNIQUE NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "plan" VARCHAR(32) DEFAULT 'FREE' NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "workspaces" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
    "name" VARCHAR(128) NOT NULL,
    "active" BOOLEAN DEFAULT TRUE NOT NULL
);
CREATE INDEX "idx_workspaces_org" ON "workspaces"("org_id");

CREATE TABLE "users" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "name" VARCHAR(128),
    "avatar_url" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "roles" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" VARCHAR(64) NOT NULL,
    "permissions" TEXT[] NOT NULL
);

CREATE TABLE "memberships" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "workspace_id" UUID NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,
    "role_id" UUID NOT NULL REFERENCES "roles"("id"),
    "joined_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "uq_user_workspace" UNIQUE ("user_id", "workspace_id")
);

CREATE TABLE "api_keys" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "workspace_id" UUID NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,
    "prefix" VARCHAR(16) NOT NULL,
    "key_hash" VARCHAR(255) UNIQUE NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "expires_at" TIMESTAMP WITH TIME ZONE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "audit_logs" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "workspace_id" UUID NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,
    "actor_id" VARCHAR(128) NOT NULL,
    "action" VARCHAR(128) NOT NULL,
    "metadata" JSONB DEFAULT '{}'::jsonb NOT NULL,
    "recorded_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE INDEX "idx_audit_logs_workspace_date" ON "audit_logs"("workspace_id", "recorded_at" DESC);`,
      endpoints: [
        {
          method: 'GET',
          path: '/api/v1/workspaces/:id/members',
          description: 'List active team members with associated RBAC roles.'
        },
        {
          method: 'POST',
          path: '/api/v1/workspaces/:id/api-keys',
          description: 'Generate a new hashed SHA-256 API token for workspace automation.'
        },
        {
          method: 'GET',
          path: '/api/v1/workspaces/:id/audit-trail',
          description: 'Query immutable security audit logs with JSON filter criteria.'
        }
      ],
      entities: [
        { name: 'Organization', fieldsCount: 5, relationships: ['1:N Workspace'] },
        { name: 'Workspace', fieldsCount: 5, relationships: ['N:1 Organization', '1:N Membership', '1:N ApiKey', '1:N AuditLog'] },
        { name: 'User', fieldsCount: 5, relationships: ['1:N Membership'] },
        { name: 'Role', fieldsCount: 3, relationships: ['1:N Membership'] },
        { name: 'Membership', fieldsCount: 5, relationships: ['N:1 User', 'N:1 Workspace', 'N:1 Role'] },
        { name: 'ApiKey', fieldsCount: 6, relationships: ['N:1 Workspace'] },
        { name: 'AuditLog', fieldsCount: 6, relationships: ['N:1 Workspace'] }
      ],
      insights: [
        {
          category: 'security',
          title: 'Row-Level Tenant Isolation',
          description: 'All read queries enforce `workspace_id` validation in middleware to prevent cross-tenant data leaks.',
          impact: 'High'
        },
        {
          category: 'indexing',
          title: 'Time-Partitioned Audit Logs',
          description: 'Audit logs benefit from composite index `(workspace_id, recorded_at DESC)` for sub-millisecond compliance queries.',
          impact: 'High'
        }
      ],
      stats: {
        totalEntities: 7,
        totalRelations: 8,
        totalEndpoints: 3,
        queryComplexityScore: 'Multi-Tenant Row-Level Isolated'
      }
    }
  }
];
